include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - _attic/**
    - test/**  # Temporaire: focus sur lib/ jusqu'à migration Riverpod 3 + Postgrest 2
    - lib/**/examples/**  # exclus de l'analyse
