include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "_attic/**"
    - "test_legacy/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Faux positif connu : @JsonKey sur paramètres de factory Freezed est valide
    # Freezed transforme ces paramètres en getters dans le code généré
    invalid_annotation_target: ignore

linter:
  rules: {}
