// Mocks generated by Mockito 5.4.6 from annotations
// in ml_pp_mvp/test/features/cours_route/screens/cours_route_filters_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ml_pp_mvp/features/cours_route/data/cours_de_route_service.dart'
    as _i2;
import 'package:ml_pp_mvp/features/cours_route/models/cdr_etat.dart' as _i5;
import 'package:ml_pp_mvp/features/cours_route/models/cours_de_route.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CoursDeRouteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoursDeRouteService extends _i1.Mock
    implements _i2.CoursDeRouteService {
  MockCoursDeRouteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CoursDeRoute>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.CoursDeRoute>>.value(
              <_i4.CoursDeRoute>[],
            ),
          )
          as _i3.Future<List<_i4.CoursDeRoute>>);

  @override
  _i3.Future<List<_i4.CoursDeRoute>> getActifs() =>
      (super.noSuchMethod(
            Invocation.method(#getActifs, []),
            returnValue: _i3.Future<List<_i4.CoursDeRoute>>.value(
              <_i4.CoursDeRoute>[],
            ),
          )
          as _i3.Future<List<_i4.CoursDeRoute>>);

  @override
  _i3.Future<_i4.CoursDeRoute?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.CoursDeRoute?>.value(),
          )
          as _i3.Future<_i4.CoursDeRoute?>);

  @override
  _i3.Future<void> create(_i4.CoursDeRoute? cours) =>
      (super.noSuchMethod(
            Invocation.method(#create, [cours]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> update(_i4.CoursDeRoute? cours) =>
      (super.noSuchMethod(
            Invocation.method(#update, [cours]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatut({
    required String? id,
    required _i4.StatutCours? to,
    bool? fromReception = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatut, [], {
              #id: id,
              #to: to,
              #fromReception: fromReception,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CoursDeRoute>> getByStatut(_i4.StatutCours? statut) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatut, [statut]),
            returnValue: _i3.Future<List<_i4.CoursDeRoute>>.value(
              <_i4.CoursDeRoute>[],
            ),
          )
          as _i3.Future<List<_i4.CoursDeRoute>>);

  @override
  _i3.Future<bool> canTransition({
    required _i5.CdrEtat? from,
    required _i5.CdrEtat? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#canTransition, [], {#from: from, #to: to}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> applyTransition({
    required String? cdrId,
    required _i5.CdrEtat? from,
    required _i5.CdrEtat? to,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyTransition, [], {
              #cdrId: cdrId,
              #from: from,
              #to: to,
              #userId: userId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<_i5.CdrEtat, int>> countByEtat() =>
      (super.noSuchMethod(
            Invocation.method(#countByEtat, []),
            returnValue: _i3.Future<Map<_i5.CdrEtat, int>>.value(
              <_i5.CdrEtat, int>{},
            ),
          )
          as _i3.Future<Map<_i5.CdrEtat, int>>);
}
