// Mocks generated by Mockito 5.4.6 from annotations
// in ml_pp_mvp/test/integration/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ml_pp_mvp/core/models/profil.dart' as _i3;
import 'package:ml_pp_mvp/core/services/auth_service.dart' as _i4;
import 'package:ml_pp_mvp/features/profil/data/profil_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfil_1 extends _i1.SmartFake implements _i3.Profil {
  _FakeProfil_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Stream<_i2.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  _i5.Future<_i2.User> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#signIn, [email, password])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfilService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfilService extends _i1.Mock implements _i6.ProfilService {
  MockProfilService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Profil?> getCurrentProfil(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentProfil, [userId]),
            returnValue: _i5.Future<_i3.Profil?>.value(),
          )
          as _i5.Future<_i3.Profil?>);

  @override
  _i5.Future<void> createProfil(_i3.Profil? profil) =>
      (super.noSuchMethod(
            Invocation.method(#createProfil, [profil]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfil(_i3.Profil? profil) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfil, [profil]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Profil?> getByCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getByCurrentUser, []),
            returnValue: _i5.Future<_i3.Profil?>.value(),
          )
          as _i5.Future<_i3.Profil?>);

  @override
  _i5.Future<_i3.Profil> createForCurrentUser({
    required String? role,
    String? nomComplet,
    String? email,
    String? depotId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createForCurrentUser, [], {
              #role: role,
              #nomComplet: nomComplet,
              #email: email,
              #depotId: depotId,
            }),
            returnValue: _i5.Future<_i3.Profil>.value(
              _FakeProfil_1(
                this,
                Invocation.method(#createForCurrentUser, [], {
                  #role: role,
                  #nomComplet: nomComplet,
                  #email: email,
                  #depotId: depotId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Profil>);

  @override
  _i5.Future<_i3.Profil> getOrCreateByCurrentUser({
    String? defaultRole = 'lecture',
    String? nomComplet,
    String? email,
    String? depotId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateByCurrentUser, [], {
              #defaultRole: defaultRole,
              #nomComplet: nomComplet,
              #email: email,
              #depotId: depotId,
            }),
            returnValue: _i5.Future<_i3.Profil>.value(
              _FakeProfil_1(
                this,
                Invocation.method(#getOrCreateByCurrentUser, [], {
                  #defaultRole: defaultRole,
                  #nomComplet: nomComplet,
                  #email: email,
                  #depotId: depotId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Profil>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#aud)),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
